### ISSUE TITLE
Error: crypto is not defined 

### ISSUE THREAD

**Issue by heartforit** [TotenDev/Cloud-Pipe#2]
Console output shows:

if (this.dataIntegrity) { dataHash = crypto.createHash('md5').update(upBuf...
ReferenceError: crypto is not defined
    at S3Api.singleUpload (**_\node_modules\cloud-pipe\node_modules
\jsss\src\S3Api.js:80:42)
    at CloudPipe.finish (**_\node_modules\cloud-pipe\src\cloud-pipe
.js:194:21)
    at CloudPipe.<anonymous> (_**\test.js:50:15)
    at CloudPipe.EventEmitter.emit (events.js:93:17)
    at JSss.CloudPipe.getReady( *__\node_modules\cloud-pipe\src\clo
ud-pipe.js:152:51)
    at JSss.EventEmitter.emit (events.js:126:20)
    at JSss.getReady (_**\node_modules\cloud-pipe\node_modules\jsss
\src\JSss.js:86:12)
    at S3Api.multipartInitiateUpload (**_\node_modules\cloud-pipe\n
ode_modules\jsss\src\S3Api.js:137:54)
    at IncomingMessage.S3Api.simpleRequest.req.on.requestResponded (_**\node_modules\cloud-pipe\node_modules\jsss\src\S3Api.js:435:15)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)

npm install crypto does not reslove this issue.

Is there anything else i am doing wrong or is there really a bug?
For info, this error get triggerd by following snipped (example from git repo):

var maxChunkSize = 10000000; //10 mb
// npm install cloud-pipe
var cp = require("cloud-pipe")("bucketName","keyID","SecretKey","file.txt",maxChunkSize);
cp.on("cp-error",function (err) {
    console.log("error",err);
});
cp.on("cp-end",function () {
    console.log("end");
});
cp.on("cp-drained",function () {
    console.log("should resume writing");
});
//Must be registered in order to CloudPipe get ready
cp.on("cp-ready",function () {
    var chunk = "OMG"
    if (!cp.write(chunk)) { /_wait until cp-drained event, and write again there_/ }
    else { cp.finish(); }
});

My node Version is:
Node version: v0.8.17

**Comment by gwdp** [comment]
Issue on JSSS as you described on JSSS repo.
